name: Check secrets

on:
  push:
    branches: [ feat-*]
jobs:
  check-secrets:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Retrieve removed commits
        run: run git fsck --lost-found 2>/dev/null || true

      - name: Run secret scanning with TruffleHog
        uses: trufflesecurity/trufflehog@v3.95.3
        with:
          path: ./
          base: ""
          head: HEAD
          extra_args: --results=verified,unknown

